version: 0.2

phases:
 build:
  command:
   - echo Entered the build phase...
   - mvn clean package
 post_build:
  command:
    - echo Build completed successfully
artifacts:
 files:
   -target/userservice.jar
 discard-paths: yes
	 
   	